
spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:8889/nspace2?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: root

nspace:
  securiry:
    token: wdliwnv234c0as9234f8237A